In [ ]:
import pandas as pd
import openpyxl
import numpy as np

In [4]:
workbook = pd.read_excel('nearest_atm3.xlsx')
workbook

,ID,governerate,region,Address,Lat,Long,ID.1,governorate1,region1,address1,...,distance1,distance1_in_meters,ID2,governerate2,region2,address2,Lat2,Long2,distance2,distance2_in_meters
0,1,Al Fayyum,Markaz Al-Fayyum,Alfayoum Beghous Alhoriea St.,29.304412,30.853546,22,Al Fayyum,Markaz Al-Fayyum,"12 Khaled Bin Al Waleed Street, Baghous, Fayoum",...,0.168,168,30,Al Fayyum,Markaz Al-Fayyum,Fayoum train station,29.308889,30.847499,0.769,769
1,2,Al Fayyum,Markaz Al-Fayyum,Fayoum University,29.319696,30.835641,33,Al Fayyum,Markaz Al-Fayyum,Fayoum University,...,0.000,0,8,Al Fayyum,Markaz Al-Fayyum,10th of Ramadan - Industrial Zone B1,29.321487,30.837896,0.296,296
2,3,Al Fayyum,Markaz Al-Fayyum,Fayoum AlHoriea St.,29.308199,30.842229,3,Al Fayyum,Markaz Al-Fayyum,Fayoum AlHoriea St.,...,0.000,0,6,Al Fayyum,Markaz Al-Fayyum,AlFayoum 45 AlHorreya St. Fayoum,29.307723,30.846140,0.383,383
3,4,Al Fayyum,Markaz Sinnuris,Sanoras - Fayoum,29.408575,30.865073,17,Al Fayyum,Markaz Sinnuris,Almadares St. Sanoras Sector Alfaioum,...,0.616,616,26,Al Fayyum,Markaz Sinnuris,Abdul Salam Aref Street - Senoras,29.415401,30.864294,0.763,763
4,5,Al Fayyum,Markaz Itsa,194 Abo Bakr AlSiddiq St.- Atsa City - Fayoum,29.236966,30.790194,29,Al Fayyum,Markaz Itsa,Omar Ibn Al-Khattab Street - next to the local...,...,0.502,502,28,Al Fayyum,Markaz Itsa,Bahr Arous Street - Atsa,29.241437,30.795185,0.694,694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,4259,As Suways,Kism Al-Arb'in,Suez Canal Authority Water Company,29.967446,32.550833,4236,As Suways,Kism Al-Arb'in,Suez Canal Authority Water Company,...,0.000,0,4262,As Suways,Kism Al-Arb'in,AlGeish St. Suez District Suez in front of Oma...,29.967901,32.553257,0.239,239
4259,4260,As Suways,Kism 'Ataqah,K 36 Suez - Ain Sokhna Road,29.728850,32.381612,4239,As Suways,Kism 'Ataqah,K 36 Suez - Ain Sokhna Road,...,0.000,0,4237,As Suways,Kism 'Ataqah,Egyptian-Chinese Joint Investment Corporation ...,29.670297,32.317752,8.969,8969
4260,4261,As Suways,Kism 'Ataqah,Suez Sokhna Road Canary Village,29.617352,32.317460,4240,As Suways,Kism 'Ataqah,Suez Sokhna Road Canary Village,...,0.000,0,4237,As Suways,Kism 'Ataqah,Egyptian-Chinese Joint Investment Corporation ...,29.670297,32.317752,5.887,5887
4261,4262,As Suways,Kism Al-Arb'in,AlGeish St. Suez District Suez in front of Oma...,29.967901,32.553257,4262,As Suways,Kism Al-Arb'in,AlGeish St. Suez District Suez in front of Oma...,...,0.000,0,4259,As Suways,Kism Al-Arb'in,Suez Canal Authority Water Company,29.967446,32.550833,0.239,239
4262,4263,As Suways,Kism Al-Arb'in,Two commercial stores numbers (12) located on ...,29.975812,32.546986,4235,As Suways,Kism Al-Arb'in,Two commercial stores numbers (12) located on ...,...,0.000,0,4228,As Suways,Kism Al-Arb'in,Corner of Talaat Harb St. and 23 July,29.970485,32.550995,0.707,707

In [ ]:
workbook.groupby('region').describe()

In [19]:
new = workbook.groupby(['region']).size()
display(new)

region
City Dishna                               11
City New Burj al-'Arab City               12
City New Minya City                        3
Kism 'Abdin                               30
Kism 'Ain Schams                          25
                                          ..
unorganized Unorganized in Aswan          13
unorganized Unorganized in Asyut           5
unorganized Unorganized in Bani Suwayf     2
unorganized Unorganized in Qina            4
unorganized Unorganized in Suhaj           2
Length: 303, dtype: int64

In [20]:
new.to_excel('num_of_atms_at_regions.xlsx', sheet_name='atms_region')